SELECT * FROM sql_sales_analysis.superstore_sales;
-- Query1 Find the Total Records
select count(*) as Total_Records
from superstore_sales;

-- Query2 Find the Total sales generated 
select round(sum(sales),2) as total_sales
from superstore_sales;

-- Query 3 -find the Total Profit Generated by the business 
select round(sum(profit),2) as  Total_profit
from superstore_sales;

-- query 4- Top 10 Sales by Sales
select
     state,
     round(sum(sales),2) as Total_sales
from superstore_sales
group by State
order by Total_Sales desc
limit 10;

-- query5 - Top 10 state by profit
select
     state,
     round(sum(profit),2) as Total_profit
from superstore_sales
group by State
order by Total_profit desc
limit 10;

-- Query 6- Identify the top 10 customers who generated the highest sales revenue for the company.
select
     `customer name`,
     round(sum(sales),2) as Total_sales
from superstore_sales
group by `Customer name`
order by Total_sales desc
limit 10;

-- query 7 Which customers generated the highest profit for the company?
select
    `Customer Name`,
    round(sum(profit),2) as Total_profit
from superstore_sales
group by `Customer Name`
order by Total_profit desc
limit 10;

-- Query 8- Top 10 Product Categories by Sales?
select
    Category,
    round(sum(sales),2) as Total_sales
from superstore_sales
group by Category
order by Total_sales desc;

-- Query 9: Top 10 Sub-Categories by Sales
select
    `Sub-Category`,
    round(sum(sales),2) as Total_sales
from superstore_sales
group by `Sub-Category`
order by Total_sales desc
limit 10;

-- Query 10: Top 10 Sub-Categories by Profit
select
    `Sub-Category`,
    round(sum(profit),2) as Total_profit
from superstore_sales
group by `Sub-Category`
order by Total_profit desc
limit 10;

-- Query 11: Region-wise Sales Analysis
select
    Region,
    round(sum(sales),2) as Total_sales
from superstore_sales
group by Region
order by Total_sales desc;
-- QUERY 12:Which regions generate the highest profit?
select
    Region,
    round(sum(profit),2) as Total_profit
from superstore_sales
group by Region
order by Total_profit desc;

-- Query13: Identify the top 10 products that generated the highest sales revenue
select
    `Product Name`,
    round(sum(sales),2) as Total_sales
from superstore_sales
group by `Product Name`
order by Total_sales desc
limit 10;

-- Query 14: Which Products Generated the Highest Profit?
select
    `Product Name`,
    round(sum(profit),2) as Total_profit
from superstore_sales
group by `Product Name`
order by Total_profit desc
limit 10;

-- Query 15: Which Products Generated the Highest Loss?
select
    `Product Name`,
    round(sum(profit),2) as Total_loss
from superstore_sales
group by `Product Name`
order by Total_loss asc
limit 10;


-- Query 16: Average Discount by Category
select
    Category,
    round(avg(discount),2) as Avg_discount
from superstore_sales
group by Category
order by Avg_discount desc;

-- Query 17: Sales and Profit by Category?
select
    Category,
    round(sum(sales),2) as Total_sales,
    round(sum(profit),2) as Total_profit
from superstore_sales
group by Category
order by Total_sales desc;

-- Query 18: Top 10 States by Quantity Sold?
select
    State,
    sum(quantity) as Total_quantity
from superstore_sales
group by State
order by Total_quantity desc
limit 10;

-- Query 19: Average Profit per Order?
select
    round(avg(profit),2) as Avg_profit_per_order
from superstore_sales;

-- Query 20: Sales Contribution by Segment
select
    Segment,
    round(sum(sales),2) as Total_sales
from superstore_sales
group by Segment
order by Total_sales desc;

-- Query 21: Profit Contribution by Segment?
select
    Segment,
    round(sum(profit),2) as Total_profit
from superstore_sales
group by Segment
order by Total_profit desc;


